In [23]:
import pandas as pd


pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)


df = pd.read_parquet("results.parquet", engine="fastparquet")
df.head().T

,0,1,2,3,4
image,10002.jpg,10002.jpg,10002.jpg,10015.jpg,10015.jpg
model,llava:13b,llava,moondream,llava:13b,llava
emotion,fear,fear,surprise,surprise,surprise
confidence,0.854,0.95,NaN,0.56722,0.95
description,"The image depicts a large building in the center, which appears to be on fire, with smoke rising from its roof and flames visible at the top floors. People are scattered around the area, some of whom seem to be watching the scene unfold. The setting suggests an urban environment, likely in the late afternoon or evening due to the long shadows on the ground and the darkening sky. There is a sense of urgency and danger conveyed by the smoke and flames engulfing the building, which might evoke feelings of fear among those present.","The image depicts a large cityscape with tall buildings in the background and a thick smoke plume rising into the sky above them, indicating an intense fire or explosion. In the foreground, there is a visible building with multiple levels, and people are present who appear to be observing the situation. The presence of the smoke suggests a dangerous and urgent event, which would elicit feelings of fear due to the potential harm or loss associated with such incidents.",None,"The image captures a unique scene on a body of water where a group of people are enjoying their time on what appears to be a traditional canoe-style boat. They seem to be traveling, with the people in the rear section facing forward, suggesting that they might be tourists or explorers taking in the sights around them. The weather is cloudy and the water calm, creating an atmosphere of serenity. The people on the boat are dressed casually, wearing hats and sunglasses to protect themselves from the sun. There is no clear expression of happiness, sadness, fear, anger or disgust.","The image shows a boat on a body of water with multiple people on it. The boat is uniquely designed to resemble a grass-roofed structure, possibly reflecting cultural practices or tourism activity in the area. It appears to be raining lightly as suggested by the overcast sky. There's no clear indication of emotions on the faces of the individuals on the boat, but the novelty and unexpectedness of the boat's design could elicit a sense of surprise in the viewer."
latency,35.0629,14.685902,3.194663,48.538311,20.118884
timestamp,1777652348.430649,1777652363.11746,1777652366.312964,1777652414.859339,1777652434.979478

In [25]:
16000*40

640000

In [24]:
df[["model", "emotion", "description"]].head(10)

,model,emotion,description
0,llava:13b,fear,"The image depicts a large building in the center, which appears to be on fire, with smoke rising from its roof and flames visible at the top floors. People are scattered around the area, some of whom seem to be watching the scene unfold. The setting suggests an urban environment, likely in the late afternoon or evening due to the long shadows on the ground and the darkening sky. There is a sense of urgency and danger conveyed by the smoke and flames engulfing the building, which might evoke feelings of fear among those present."
1,llava,fear,"The image depicts a large cityscape with tall buildings in the background and a thick smoke plume rising into the sky above them, indicating an intense fire or explosion. In the foreground, there is a visible building with multiple levels, and people are present who appear to be observing the situation. The presence of the smoke suggests a dangerous and urgent event, which would elicit feelings of fear due to the potential harm or loss associated with such incidents."
2,moondream,surprise,None
3,llava:13b,surprise,"The image captures a unique scene on a body of water where a group of people are enjoying their time on what appears to be a traditional canoe-style boat. They seem to be traveling, with the people in the rear section facing forward, suggesting that they might be tourists or explorers taking in the sights around them. The weather is cloudy and the water calm, creating an atmosphere of serenity. The people on the boat are dressed casually, wearing hats and sunglasses to protect themselves from the sun. There is no clear expression of happiness, sadness, fear, anger or disgust."
4,llava,surprise,"The image shows a boat on a body of water with multiple people on it. The boat is uniquely designed to resemble a grass-roofed structure, possibly reflecting cultural practices or tourism activity in the area. It appears to be raining lightly as suggested by the overcast sky. There's no clear indication of emotions on the faces of the individuals on the boat, but the novelty and unexpectedness of the boat's design could elicit a sense of surprise in the viewer."
5,moondream,surprise,None
6,llava:13b,sadness,"In the image, there are two individuals in a room. The person on the left side of the image is sitting on the floor with their legs crossed, wearing a white robe and holding a cigarette. This individual has an expression that seems to reflect sadness or contemplation. The person on the right side of the image is lying down on a bed, appearing to be sleeping. The room has a minimalistic design, with a plain wall in the background and no significant objects visible. The overall mood conveyed by this image suggests a quiet, intimate moment between the two individuals."
7,llava,fear,"The image shows a couple lying on a bed in what appears to be an unoccupied room. One individual is looking over their shoulder with a fearful expression, while the other is sleeping peacefully. The overall atmosphere of the scene suggests a sense of vulnerability and emotional tension, which could imply that they are worried about something or experiencing a moment of uncertainty. The stark contrast between the two individuals' states reflects the complexity of human emotions and how they can be influenced by external factors or individual circumstances."
8,moondream,None,None